// <auto-generated />
using AnimalShelterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelterApi.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20201030164931_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterApi.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("AnimalName");

                    b.Property<string>("AnimalType");

                    b.Property<string>("Breed");

                    b.Property<string>("Details");

                    b.Property<string>("Sex");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 3,
                            AnimalName = "Roger",
                            AnimalType = "Cat",
                            Breed = "Mancoon",
                            Details = "Roger is a Large Orange Mancoon cat that is fixed and shots are current. would be great with a family that has kids.",
                            Sex = "Male"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 2,
                            AnimalName = "Goose",
                            AnimalType = "Dog",
                            Breed = "Labrador Retriever",
                            Details = "Goose is a fun,well mannered dog that was recently surrendered to us because his owner recently passed. he is fixed and up to date on his shots. he would be great for all families and is great with kids and other animals.",
                            Sex = "Male"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 7,
                            AnimalName = "Skittles",
                            AnimalType = "Cat",
                            Breed = "Tabby",
                            Details = "Skittles is an older female cat that would do well in a small family with older kids, She is best by herself and has never been around dogs.",
                            Sex = "Female"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 1,
                            AnimalName = "Beau",
                            AnimalType = "Dog",
                            Breed = "Coon Hound",
                            Details = "Beau is a typical Coon hound. he likes to play and is just now coming into his body. he is uncoordinated still a little but loves being around kids and his nose can still get him into a little trouble. great family dog",
                            Sex = "Male"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
